import "./src/javascript/exo1.js"
import "./src/javascript/exo2.js"
import "./src/javascript/exo3.js"
import "./src/javascript/exo4.js"
import "./src/javascript/exo5.js"
import "./src/javascript/exo6.js"
import "./src/javascript/exo7.js"
